/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AllUnitsConversion {
  'inputUnit' : UnitType,
  'inputValue' : number,
  'conversions' : Array<[UnitType, number]>,
}
export interface ConversionResult {
  'convertedValue' : number,
  'toUnit' : UnitType,
  'fromUnit' : UnitType,
  'inputValue' : number,
}
export type UnitCategory = string;
export interface UnitMetadata {
  'displayName' : string,
  'category' : UnitCategory,
  'symbol' : string,
}
export type UnitType = string;
export interface _SERVICE {
  'clearUnitData' : ActorMethod<[], undefined>,
  'convertArea' : ActorMethod<
    [UnitType, UnitType, number],
    [] | [ConversionResult]
  >,
  'convertToAllUnits' : ActorMethod<
    [UnitType, number],
    [] | [AllUnitsConversion]
  >,
  'getSupportedUnits' : ActorMethod<[], Array<UnitType>>,
  'getUnitMetadata' : ActorMethod<[], Array<[UnitType, UnitMetadata]>>,
  'initializeUnits' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];