/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UnitType = IDL.Text;
export const ConversionResult = IDL.Record({
  'convertedValue' : IDL.Float64,
  'toUnit' : UnitType,
  'fromUnit' : UnitType,
  'inputValue' : IDL.Float64,
});
export const AllUnitsConversion = IDL.Record({
  'inputUnit' : UnitType,
  'inputValue' : IDL.Float64,
  'conversions' : IDL.Vec(IDL.Tuple(UnitType, IDL.Float64)),
});
export const UnitCategory = IDL.Text;
export const UnitMetadata = IDL.Record({
  'displayName' : IDL.Text,
  'category' : UnitCategory,
  'symbol' : IDL.Text,
});

export const idlService = IDL.Service({
  'clearUnitData' : IDL.Func([], [], []),
  'convertArea' : IDL.Func(
      [UnitType, UnitType, IDL.Float64],
      [IDL.Opt(ConversionResult)],
      ['query'],
    ),
  'convertToAllUnits' : IDL.Func(
      [UnitType, IDL.Float64],
      [IDL.Opt(AllUnitsConversion)],
      ['query'],
    ),
  'getSupportedUnits' : IDL.Func([], [IDL.Vec(UnitType)], ['query']),
  'getUnitMetadata' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(UnitType, UnitMetadata))],
      ['query'],
    ),
  'initializeUnits' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UnitType = IDL.Text;
  const ConversionResult = IDL.Record({
    'convertedValue' : IDL.Float64,
    'toUnit' : UnitType,
    'fromUnit' : UnitType,
    'inputValue' : IDL.Float64,
  });
  const AllUnitsConversion = IDL.Record({
    'inputUnit' : UnitType,
    'inputValue' : IDL.Float64,
    'conversions' : IDL.Vec(IDL.Tuple(UnitType, IDL.Float64)),
  });
  const UnitCategory = IDL.Text;
  const UnitMetadata = IDL.Record({
    'displayName' : IDL.Text,
    'category' : UnitCategory,
    'symbol' : IDL.Text,
  });
  
  return IDL.Service({
    'clearUnitData' : IDL.Func([], [], []),
    'convertArea' : IDL.Func(
        [UnitType, UnitType, IDL.Float64],
        [IDL.Opt(ConversionResult)],
        ['query'],
      ),
    'convertToAllUnits' : IDL.Func(
        [UnitType, IDL.Float64],
        [IDL.Opt(AllUnitsConversion)],
        ['query'],
      ),
    'getSupportedUnits' : IDL.Func([], [IDL.Vec(UnitType)], ['query']),
    'getUnitMetadata' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(UnitType, UnitMetadata))],
        ['query'],
      ),
    'initializeUnits' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };