/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CalculationRecord = IDL.Record({
  'id' : IDL.Nat,
  'inputSummary' : IDL.Text,
  'timestamp' : IDL.Int,
  'category' : IDL.Text,
  'calculatorName' : IDL.Text,
  'resultSummary' : IDL.Text,
});
export const PopularCalculator = IDL.Record({
  'usageCount' : IDL.Nat,
  'category' : IDL.Text,
  'calculatorName' : IDL.Text,
});

export const idlService = IDL.Service({
  'clearHistory' : IDL.Func([], [], []),
  'getCalculationHistory' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(CalculationRecord)],
      ['query'],
    ),
  'getPopularCalculators' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(PopularCalculator)],
      ['query'],
    ),
  'logCalculation' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CalculationRecord = IDL.Record({
    'id' : IDL.Nat,
    'inputSummary' : IDL.Text,
    'timestamp' : IDL.Int,
    'category' : IDL.Text,
    'calculatorName' : IDL.Text,
    'resultSummary' : IDL.Text,
  });
  const PopularCalculator = IDL.Record({
    'usageCount' : IDL.Nat,
    'category' : IDL.Text,
    'calculatorName' : IDL.Text,
  });
  
  return IDL.Service({
    'clearHistory' : IDL.Func([], [], []),
    'getCalculationHistory' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(CalculationRecord)],
        ['query'],
      ),
    'getPopularCalculators' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(PopularCalculator)],
        ['query'],
      ),
    'logCalculation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };